# ---------------------------------------------------------------------------- #
## \file Makefile
## \author Sebastien Beaugrand
## \sa http://beaugrand.chez.com/
## \copyright CeCILL 2.1 Free Software license
# ---------------------------------------------------------------------------- #
.PHONY: all
all:\
 build\
 build/lifiReceiver-B_Cu.pdf\
 build/lifiReceiver-F_SilkS.pdf\
 build/lifiReceiverSchema.pdf\

include ../../makefiles/kibot.mk
